# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    filter_sets:
        thumbarticle:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        thumbarticletable:
            quality: 85
            filters:
                thumbnail:
                    size: [ 200, 100 ]
                    mode: outbound
        thumbuseravatar:
            quality: 85
            filters:
                thumbnail:
                    size: [ 120, 120 ]
                    mode: outbound
