vich_uploader:
    db_driver: orm
    mappings:
      article_picture:
        uri_prefix: '/uploads/article/images'
        upload_destination: '%kernel.project_dir%/public/uploads/article/images'
        namer:
          service: Vich\UploaderBundle\Naming\HashNamer
          options: { algorithm: 'sha256', length: 50 }

        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true

      user_avatar:
        uri_prefix: '/uploads/user/avatar'
        upload_destination: '%kernel.project_dir%/public/uploads/user/avatar'
        namer:
          service: Vich\UploaderBundle\Naming\HashNamer
          options: { algorithm: 'sha256', length: 50 }

        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
